version: ~> 1.0
language: scala

before_install:
  - curl -Ls https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | JABBA_VERSION=0.11.2 bash && . ~/.jabba/jabba.sh
  # Travis-CI has (as of March 2021, anyway) an outdated sbt-extras version,
  # so overwrite it with a March 2021 version that works with sbt 1.4.8+
  - |
    curl -sL https://raw.githubusercontent.com/paulp/sbt-extras/dc4f350f112580fcdf5f6fa7e8d5d2116475f84a/sbt  > /tmp/sbt-launch-script || travis_terminate 1
    chmod +x /tmp/sbt-launch-script || travis_terminate 1
    sudo mv /tmp/sbt-launch-script /usr/local/bin/sbt || travis_terminate 1

install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

git:
  depth: false # Avoid sbt-dynver not seeing the tag

jobs:
  include:
    - stage: test
      name: "Validations"
      script: sbt scalafmtCheckAll scalafmtSbtCheck mimaReportBinaryIssues
      env:
        - TRAVIS_JDK=11

    - name: "Run tests on AdoptOpenJDK 11"
      script: sbt +test
      env:
        - TRAVIS_JDK=11

    - name: "Run tests on AdoptOpenJDK 8"
      script: sbt +test
      env:
        - TRAVIS_JDK=8

# TODO replace with Sonatype
#    - stage: publish
#      name: "Publish artifacts to Bintray"
#      script: sbt +publish
#      env:
#        - TRAVIS_JDK=11

stages:
  - name: test
  - name: publish
    if: ((branch = main AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba"
    - "$HOME/.sbt"

before_cache:
  - rm -rf $HOME/.ivy2/cache/com.lightbend.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.lightbend.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

branches:
  only:
    - main
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^\d+\.\d+(\.\d+)?\.x$/
